---
title: "Oridinal Logistic Regression"
author: "Ian Dinwoodie"
date: "4/7/2020"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(MASS)
library(AER)
opts_chunk$set(echo=TRUE)
set.seed(1)
```

# General Setup

Load the dataframe and check the dimensions. We expect 963 rows and 298 columns.

```{r}
# Load the data from the csv into a data frame.
df.orig <- read.csv("data/processed.csv", header=TRUE)

# Get the original data frame dimensions.
dim(df.orig)
```

Address columns that need corrections.

```{r}
# Convert "dog_sex" into "male" columns.
df.mod <- df.orig
#df.mod$male <- ifelse(df.mod$dog_sex==1, 1, 0)

# To correct the "dog_spayed" column we convert "idk" responses to NA.
#summary(df.mod$dog_spayed)
#df.mod$dog_spayed[df.mod$dog_spayed>1] <- NA
#summary(df.mod$dog_spayed)

# Create dummy variables for the levels 1-4 of "behavior_prog".
# We ignore levels 5 and 6 because they are irrelevant to the question.
df.mod$behavior_prog_1 <- ifelse(df.mod$behavior_prog==1, 1, 0)
df.mod$behavior_prog_1[is.na(df.mod$behavior_prog_1)] <- 0
df.mod$behavior_prog_1 <- as.integer(df.mod$behavior_prog_1)
df.mod$behavior_prog_2 <- ifelse(df.mod$behavior_prog==2, 1, 0)
df.mod$behavior_prog_2[is.na(df.mod$behavior_prog_2)] <- 0
df.mod$behavior_prog_2 <- as.integer(df.mod$behavior_prog_2)
df.mod$behavior_prog_3 <- ifelse(df.mod$behavior_prog==3, 1, 0)
df.mod$behavior_prog_3[is.na(df.mod$behavior_prog_3)] <- 0
df.mod$behavior_prog_3 <- as.integer(df.mod$behavior_prog_3)
df.mod$behavior_prog_4 <- ifelse(df.mod$behavior_prog==4, 1, 0)
df.mod$behavior_prog_4[is.na(df.mod$behavior_prog_4)] <- 0
df.mod$behavior_prog_4 <- as.integer(df.mod$behavior_prog_4)
```

Retain only needed columns.

```{r}
# Retain only the columns to be used for analysis.
predictors <- c(
#  '^male$',
#  '^dog_spayed$',
  '^prof_type_\\d$',
  '^training_methods_\\d$',
  '^equipment_\\d+$',
  '^med_list_\\d+$',
  '^alt_med_type_\\d+$',
  '^behavior_prog_\\d+$',
  '^behavior_tech_used_\\d+$'
)
outcomes <- c(
  "^agg_\\S+$"
)
pattern <- paste(c(predictors, outcomes), collapse='|')
idx <- grep(pattern, names(df.mod))
df.mod <- df.mod[, idx]
dim(df.mod)
```

```{r}
# Drop the columns that do not meet the minimum response cutoff.
binaries <- c(
  '^prof_type_\\d$',
  '^training_methods_\\d$',
  '^equipment_\\d+$',
  '^med_list_\\d+$',
  '^alt_med_type_\\d+$',
  '^behavior_tech_used_\\d+$'
)
pattern <- paste(binaries, collapse='|')
idx.binaries <- grep(pattern, names(df.mod))
drops <- NULL
for (idx in idx.binaries) {
  # We record any column with less than 10 affirmative (1) responses.
  if (sum(df.mod[,idx]) < 10) {
    drops <- c(drops, idx)
  }
}
print(names(df.mod)[drops])
df.mod <- subset(df.mod, select=-drops)

# Examine the data frame.
#summary(df.mod)
```

We also wrap reusable code in functions.

```{r}
get_agg_data_frame <- function(df, pred.patterns, outcome, excludes)
{
  pattern <- paste(c(pred.patterns, outcome), collapse='|')
  idx <- grep(pattern, names(df))
  df.out <- df[, idx]
  
  # Format the outcome as a factor with order.
  df.out[,outcome] <- round(df.out[,outcome], 0)
  df.out[,outcome] <- factor(df.out[,outcome], levels=c("1","2","3","4","5","6","7"),
                             ordered=TRUE)
  
  if (length(excludes) > 0) {
    # Exclude variables that cause issues for the model.
    df.out <- df.out[, !colnames(df.out) %in% excludes]
  }
  
  # Drop rows with null values for the outcome.
  df.out <- df.out[!is.na(df.out[,outcome]), ]
  
  return(df.out)
}

apply_binary_response_criteria <- function(df)
{
  binaries <- c(
    '^prof_type_\\d$',
    '^training_methods_\\d$',
    '^equipment_\\d+$',
    '^med_list_\\d+$',
    '^alt_med_type_\\d+$',
    '^behavior_tech_used_\\d+$'
  )
  
  pattern <- paste(binaries, collapse='|')
  idx.binaries <- grep(pattern, names(df))
  drops <- NULL
  for (idx in idx.binaries) {
    # We record any column with less than 10 affirmative (1) responses.
    if (sum(df[,idx]) < 10) {
      drops <- c(drops, idx)
    }
  }
  
  if (length(drops) > 0) {
    # Drop the columns that did not meet the minimum response cutoff.
    df <- subset(df, select=-drops)
  }
  
  return(df)
}
```

# Overall Aggression

```{r}
# Generate the desired subset data frame.
outcome <- "agg_avg"
excludes <- vector()
df.agg <- get_agg_data_frame(df.mod, predictors, outcome, excludes)
df.agg <- apply_binary_response_criteria(df.agg)
dim(df.agg)
#summary(df.agg)

# Fit a logistic regression.
f <- as.formula(paste0(outcome, "~", "."))
m <- polr(f, data=df.agg, Hess=TRUE)
summary(m)

# Generate CIs and p-values.
coeftest(m) # p-values
ci <- confint.default(m)
exp(cbind(OR = coef(m), ci)) # OR and CI
```

Attempt to find a better fit.

```{r}
# Fit a logistic regression.
#f <- as.formula(paste0(outcome, "~", "."))
#m <- polr(f, data=df.agg, Hess=TRUE)
##m.step<- stepAIC(m, trace=FALSE)

# Generate CIs and p-values.
#coeftest(m.step) # p-values
#ci <- confint.default(m.step)
#exp(cbind(OR = coef(m.step), ci)) # OR and CI
```

# Conflict Aggression

```{r}
# Generate the desired subset data frame.
outcome <- "agg_conf"
df.agg <- get_agg_data_frame(df.mod, predictors, outcome, excludes)
df.agg <- apply_binary_response_criteria(df.agg)
dim(df.agg)
#summary(df.agg)

# Fit a logistic regression.
f <- as.formula(paste0(outcome, "~", "."))
coef <- rep(0, length(df.agg)-1)
zeta <- seq(from=0, to=1, length.out=6)
start <- c(coef, zeta)
str(df.agg)
m <- polr(f, data=df.agg, Hess=TRUE, start=start)
summary(m)

# Generate CIs and p-values.
coeftest(m) # p-values
ci <- confint.default(m)
exp(cbind(OR = coef(m), ci)) # OR and CI
```

```{r}
# Fit a logistic regression.
#m.step<- stepAIC(m, trace=FALSE)

# Generate CIs and p-values.
#coeftest(m.step) # p-values
#ci <- confint.default(m.step)
#exp(cbind(OR = coef(m.step), ci)) # OR and CI
```

# I.D.H. Aggression

```{r}
# Generate the desired subset data frame.
outcome <- "agg_idh"
df.agg <- get_agg_data_frame(df.mod, predictors, outcome, excludes)
df.agg <- apply_binary_response_criteria(df.agg)
dim(df.agg)
#summary(df.agg)

# Fit a logistic regression.
f <- as.formula(paste0(outcome, "~", "."))
m <- polr(f, data=df.agg, Hess=TRUE)
summary(m)

# Generate CIs and p-values.
coeftest(m) # p-values
ci <- confint(m)
print(ci)
exp(cbind(OR = coef(m), ci)) # OR and CI
```

# External Aggression (People)

```{r}
# Generate the desired subset data frame.
outcome <- "agg_ext_ppl"
df.agg <- get_agg_data_frame(df.mod, predictors, outcome, excludes)
df.agg <- apply_binary_response_criteria(df.agg)
dim(df.agg)
#summary(df.agg)

# Fit a logistic regression.
f <- as.formula(paste0(outcome, "~", "."))
coef <- rep(0, length(df.agg)-1)
zeta <- seq(from=0, to=1, length.out=6)
start <- c(coef, zeta)
m <- polr(f, data=df.agg, Hess=TRUE, start=start)
summary(m)

# Generate CIs and p-values.
coeftest(m) # p-values
ci <- confint.default(m)
exp(cbind(OR = coef(m), ci)) # OR and CI
```

# External Aggression (Dogs)

```{r}
# Generate the desired subset data frame.
outcome <- "agg_ext_dog"
df.agg <- get_agg_data_frame(df.mod, predictors, outcome, excludes)
df.agg <- apply_binary_response_criteria(df.agg)
dim(df.agg)
#summary(df.agg)

# Fit a logistic regression.
f <- as.formula(paste0(outcome, "~", "."))
coef <- rep(0, length(df.agg)-1)
zeta <- seq(from=0, to=1, length.out=6)
start <- c(coef, zeta)
m <- polr(f, data=df.agg, Hess=TRUE, start=start)
summary(m)

# Generate CIs and p-values.
coeftest(m) # p-values
ci <- confint.default(m)
exp(cbind(OR = coef(m), ci)) # OR and CI
```

# Predatory Aggression

```{r}
# Generate the desired subset data frame.
outcome <- "agg_pred"
df.agg <- get_agg_data_frame(df.mod, predictors, outcome, excludes)
df.agg <- apply_binary_response_criteria(df.agg)
dim(df.agg)
#summary(df.agg)

# Fit a logistic regression.
f <- as.formula(paste0(outcome, "~", "."))
coef <- rep(0, length(df.agg)-1)
zeta <- seq(from=0, to=1, length.out=6)
start <- c(coef, zeta)
m <- polr(f, data=df.agg, Hess=TRUE, start=start)
summary(m)

# Generate CIs and p-values.
coeftest(m) # p-values
ci <- confint.default(m)
exp(cbind(OR = coef(m), ci)) # OR and CI
```
